-- Closes three gaps found in Phase 8's own post-implementation review:
--   1. Orgs hit the hard lock with zero advance warning — no "trial ends
--      soon" notice before it happens.
--   2. invoice.payment_failed was logged only, never surfaced to anyone.
--   3. Seat count only resyncs on manual button-press or member removal —
--      a growing roster (invite acceptance) silently undercounts until
--      then. compute_org_seat_count can't be reused as-is for a daily
--      background job (it deliberately returns null for any caller that
--      isn't a member of the org, via is_member_of_org(..., auth.uid()) —
--      auth.uid() is null outside a real user session), so
--      billing-daily-checks queries tour_members/tours directly instead,
--      which is fine: it always runs as service_role, which bypasses RLS
--      entirely anyway.
--
-- All three are handled by one new scheduled edge function
-- (billing-daily-checks) plus a small addition to stripe-webhook for #2,
-- which is genuinely event-driven rather than a once-a-day check.

-- Tracks whether the "trial ends soon" push has already gone out for this
-- org's current trial, so the daily job doesn't re-send it every run
-- until the trial actually resolves (subscribed or locked).
alter table organizations add column trial_warning_sent_at timestamptz;

-- Stripe recommends dedup'ing webhook events by id — retries and
-- redelivery are expected, not exceptional. The org-status write itself
-- is naturally idempotent (it just overwrites with the latest state), but
-- the new payment-failed notification below is a *side effect*, not a
-- state write, and side effects aren't idempotent for free: without this,
-- a redelivered invoice.payment_failed could push the same "your payment
-- failed" alert twice. service_role-only table — no policies needed
-- since no client should ever read or write this directly (RLS enabled,
-- default-deny, matching this repo's enable-RLS-on-every-table convention).
create table stripe_webhook_events (
  event_id text primary key,
  received_at timestamptz not null default now()
);
alter table stripe_webhook_events enable row level security;

-- pg_cron/pg_net: both available as installable extensions on Supabase's
-- hosted Postgres. If this statement fails with a permissions error on
-- push, they need enabling once via Dashboard → Database → Extensions
-- before re-running this migration.
create extension if not exists pg_cron with schema extensions;
create extension if not exists pg_net with schema extensions;

-- Daily at 14:00 UTC. The function is protected by a shared secret
-- (x-cron-secret header, checked against the CRON_SECRET function
-- secret) rather than a Supabase JWT — verify_jwt is set to false for
-- this function in config.toml, same reasoning as stripe-webhook: there
-- is no real user session to scope a JWT to for a scheduled job.
--
-- The secret embedded below is self-generated by this app (not a Stripe
-- or Supabase credential) and its only capability is triggering this
-- harmless, idempotent reconciliation job early/extra — low enough
-- stakes to live in a migration, but still rotatable: generate a new
-- value, update it here AND via `supabase secrets set CRON_SECRET=...`.
select cron.schedule(
  'billing-daily-checks',
  '0 14 * * *',
  $$
  select net.http_post(
    url := 'https://cypdsfoleygalkwshbor.supabase.co/functions/v1/billing-daily-checks',
    headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', 'FpdTY-5UhkFh2hM3Zla3Lc2rLX2Fm_LXxYzZ_SWQJCo'),
    body := '{}'::jsonb
  );
  $$
);